# =========================================================
# CONFIGURATION FILE FOR AZURE ML INFRASTRUCTURE - AUTO MPG
# =========================================================
variables:

  # ===============
  # GLOBAL SETTINGS
  # ===============
  ap_vm_image: ubuntu-20.04  # Virtual machine image for compute nodes
  location: eastus  # Azure region
  environment: prod  # Deployment environment

  # ==============================================
  # PROJECT-SPECIFIC SETTINGS (CHANGE PER PROJECT)
  # ==============================================
  namespace: streaming-used-car-sales-workspace  # Change per mlops project
  postfix: 001  # Unique postfix for naming consistency

  # ===============
  # ENABLE FEATURES
  # ===============
  enable_aml_computecluster: true  # Enable Azure ML compute clusters
  enable_aml_secure_workspace: true  # Enable workspace security
  enable_monitoring: false  # Disable monitoring for now (can be enabled later)

  # ================================
  # AZURE DEVOPS SERVICE CONNECTIONS
  # ================================
  ado_service_connection_rg: Azure-ARM-Prod  # Service connection for resource group
  ado_service_connection_aml_ws: Azure-ARM-Prod  # Service connection for Azure ML workspace

  # ===================
  # PIPELINE REFERENCES
  # ===================
  resource_group: default_resource_group  # Ensure correct Azure resource group
  aml_workspace: car-sales-mlops-azure-cicd-pipe  # Ensure correct Azure ML workspace
