# =========================================================
# PIPELINE CONFIGURATION FILE FOR USED CAR SALES PREDICTION
# =========================================================
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

# =========================
# PROJECT-SPECIFIC SETTINGS
# =========================
display_name: used_car_sales_pipeline
description: Pipeline for training and evaluating Used Car Sales Price Prediction model

# ====================
# INPUT DATA REFERENCE
# ====================
inputs:
  input_data:
    type: uri_file
    path: azureml:streaming-used-car-sales-data@latest  # ==== REFERENCE TO DATASET IN AZURE ML ====

# =====================================
# PIPELINE JOBS - TRAINING & EVALUATION
# =====================================
jobs:
  train_model:
    type: command
    component: ../train.yml  # ==== TRAINING COMPONENT ====
    inputs:
      train_data: ${{parent.inputs.input_data}}
      test_data: ${{parent.inputs.input_data}}
    outputs:
      model_output: ${{parent.outputs.model_output}}
