# .github/workflows/ci.yml
name: cli-jobs-pipelines-used-car-sales

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - run-job.sh
      - setup.sh
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run setup script
      run: bash setup.sh
      continue-on-error: true

    - name: Run job (use newpipeline)
      run: bash -x ./run-job.sh mlops/azureml/train/newpipeline.yml
