# ===================================================================================================
# GITHUB ACTIONS WORKFLOW FOR TRAINING AND DEPLOYING STREAMING USED CAR SALES ML PIPELINE ON AZURE ML
# ===================================================================================================
name: deploy-model-training-pipeline

# ==================================================
# WORKFLOW TRIGGERS - PUSH TO MAIN - PULLS FROM MAIN
# ==================================================
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # ==== ADD MANUAL EXECUTION OPTION ====

jobs:

  # =============================================
  # RUN TRAINING PIPELINE streaming-used-car-sales
  # =============================================
  run-pipeline:
      needs: [get-config, register-environment, create-compute, register-dataset]
      uses: Azure/mlops-templates/.github/workflows/run-pipeline.yml@main
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
        parameters-file: mlops/azureml/train/newpipeline.yml
        job-name: streaming-used-car-sales-mlops-pipeline
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
